import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

// Generated by `dart run build_runner build`.
part 'app_database.g.dart';

// --- Tables ---------------------------------------------------------------
// @DataClassName gives the generated row classes a "Row" suffix, so they
// are not confused with the domain classes (Instrument, WeeklyCandle...).

/// The 30 assets of assets/catalog.json, copied here at startup.
@DataClassName('InstrumentRow')
class Instruments extends Table {
  TextColumn get symbol => text()();
  TextColumn get name => text()();

  /// "stock", "etf" or "crypto".
  TextColumn get type => text()();
  TextColumn get currency => text()();
  TextColumn get exchange => text().nullable()();
  BoolColumn get peaEligible => boolean()();
  TextColumn get description => text()();

  /// Order of the asset in catalog.json, used to load prices in that order.
  IntColumn get position => integer()();

  @override
  Set<Column> get primaryKey => {symbol};
}

/// Every weekly candle we downloaded. Shared by the catalogue, the detail
/// screen and the game.
@DataClassName('CandleRow')
class WeeklyCandles extends Table {
  TextColumn get symbol => text()();
  DateTimeColumn get date => dateTime()();
  RealColumn get open => real()();
  RealColumn get high => real()();
  RealColumn get low => real()();
  RealColumn get close => real()();
  RealColumn get volume => real().nullable()();

  // One candle per asset and per week: saving it again replaces it.
  @override
  Set<Column> get primaryKey => {symbol, date};
}

@DataClassName('FavoriteRow')
class Favorites extends Table {
  TextColumn get symbol => text()();
  DateTimeColumn get addedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {symbol};
}

/// What we know about the freshness of each asset's data.
@DataClassName('CacheMetaRow')
class CacheMeta extends Table {
  TextColumn get symbol => text()();

  /// Last successful download of the series. Null: never downloaded.
  DateTimeColumn get lastFetchedAt => dateTime().nullable()();

  /// Null: never asked. Empty string: asked, Twelve Data has no logo, so
  /// we never ask again (it would waste a credit).
  TextColumn get logoUrl => text().nullable()();

  @override
  Set<Column> get primaryKey => {symbol};
}

// --- DAOs -----------------------------------------------------------------
// A DAO groups the queries of one table, so the repository reads like
// "candlesDao.lastCandles(...)" and never writes SQL itself.

@DriftAccessor(tables: [Instruments])
class InstrumentsDao extends DatabaseAccessor<AppDatabase>
    with _$InstrumentsDaoMixin {
  InstrumentsDao(super.attachedDatabase);

  /// Inserts the catalogue, or updates it if catalog.json changed.
  Future<void> upsertAll(List<InstrumentsCompanion> rows) {
    return batch((b) => b.insertAllOnConflictUpdate(instruments, rows));
  }

  /// All instruments in catalogue order.
  Future<List<InstrumentRow>> allInstruments() {
    return (select(
      instruments,
    )..orderBy([(t) => OrderingTerm.asc(t.position)])).get();
  }

  Future<InstrumentRow?> instrument(String symbol) {
    return (select(
      instruments,
    )..where((t) => t.symbol.equals(symbol))).getSingleOrNull();
  }
}

@DriftAccessor(tables: [Favorites])
class FavoritesDao extends DatabaseAccessor<AppDatabase>
    with _$FavoritesDaoMixin {
  FavoritesDao(super.attachedDatabase);

  Future<Set<String>> favoriteSymbols() async {
    final rows = await select(favorites).get();
    return {for (final row in rows) row.symbol};
  }

  Future<void> setFavorite(String symbol, bool isFavorite) async {
    if (isFavorite) {
      await into(favorites).insertOnConflictUpdate(
        FavoritesCompanion.insert(symbol: symbol, addedAt: DateTime.now()),
      );
    } else {
      await (delete(favorites)..where((t) => t.symbol.equals(symbol))).go();
    }
  }
}

@DriftAccessor(tables: [WeeklyCandles])
class CandlesDao extends DatabaseAccessor<AppDatabase> with _$CandlesDaoMixin {
  CandlesDao(super.attachedDatabase);

  /// All candles of [symbol], oldest first.
  Future<List<CandleRow>> allCandles(String symbol) {
    return (select(weeklyCandles)
          ..where((t) => t.symbol.equals(symbol))
          ..orderBy([(t) => OrderingTerm.asc(t.date)]))
        .get();
  }

  /// The [count] most recent candles of [symbol], oldest first.
  Future<List<CandleRow>> lastCandles(String symbol, int count) async {
    final newestFirst =
        await (select(weeklyCandles)
              ..where((t) => t.symbol.equals(symbol))
              ..orderBy([(t) => OrderingTerm.desc(t.date)])
              ..limit(count))
            .get();
    return newestFirst.reversed.toList();
  }

  /// Adds new candles and overwrites the ones that already exist
  /// (same symbol and date), e.g. the current, unfinished week.
  Future<void> upsertCandles(List<WeeklyCandlesCompanion> rows) {
    return batch((b) => b.insertAllOnConflictUpdate(weeklyCandles, rows));
  }

  /// Deletes the whole series and saves [rows] instead, in one transaction
  /// so the app never sees a half-empty series.
  Future<void> replaceSeries(String symbol, List<WeeklyCandlesCompanion> rows) {
    return transaction(() async {
      await (delete(weeklyCandles)..where((t) => t.symbol.equals(symbol))).go();
      await batch((b) => b.insertAll(weeklyCandles, rows));
    });
  }
}

@DriftAccessor(tables: [CacheMeta])
class CacheMetaDao extends DatabaseAccessor<AppDatabase>
    with _$CacheMetaDaoMixin {
  CacheMetaDao(super.attachedDatabase);

  /// Cache info of every asset, by symbol.
  Future<Map<String, CacheMetaRow>> allMeta() async {
    final rows = await select(cacheMeta).get();
    return {for (final row in rows) row.symbol: row};
  }

  Future<CacheMetaRow?> metaFor(String symbol) {
    return (select(
      cacheMeta,
    )..where((t) => t.symbol.equals(symbol))).getSingleOrNull();
  }

  /// Saves the download time without touching the logo column.
  Future<void> markFetched(String symbol, DateTime at) {
    return into(cacheMeta).insert(
      CacheMetaCompanion.insert(symbol: symbol, lastFetchedAt: Value(at)),
      onConflict: DoUpdate((_) => CacheMetaCompanion(lastFetchedAt: Value(at))),
    );
  }

  /// Saves the logo URL ([url] null means "no logo") without touching the
  /// download time.
  Future<void> saveLogo(String symbol, String? url) {
    final value = Value(url ?? '');
    return into(cacheMeta).insert(
      CacheMetaCompanion.insert(symbol: symbol, logoUrl: value),
      onConflict: DoUpdate((_) => CacheMetaCompanion(logoUrl: value)),
    );
  }
}

// --- Database ---------------------------------------------------------------

@DriftDatabase(
  tables: [Instruments, WeeklyCandles, Favorites, CacheMeta],
  daos: [InstrumentsDao, FavoritesDao, CandlesDao, CacheMetaDao],
)
class AppDatabase extends _$AppDatabase {
  /// Without argument: the real SQLite file on the phone.
  /// Tests pass an in-memory database instead.
  AppDatabase([QueryExecutor? executor])
    : super(executor ?? driftDatabase(name: 'lucide'));

  // Increase this number and add a migration when a table changes.
  @override
  int get schemaVersion => 1;
}
